current_user:
  welcome:
    index: true
    destroy: false
  books: true
  end_of_services: false
  sessions:
    index: false
  stores:
    new: admin?
  sys_admin/: sys_admin?   
  sys_admin/sys_config:
    show: true
    edit: sys_admin?
 